// This file is auto-generated by @hey-api/openapi-ts

export { appControllerGetHello, type Options } from './sdk.gen';
export type { AppControllerGetHelloData, AppControllerGetHelloResponses, ClientOptions } from './types.gen';
