// This file is auto-generated by @hey-api/openapi-ts

import type { AiExampleControllerChatResponse } from './types.gen';

const chatMessageWithSchemaTypeSchemaResponseTransformer = (data: any) => {
    if (data.metadata) {
        if (data.metadata.timestamp) {
            data.metadata.timestamp = new Date(data.metadata.timestamp);
        }
    }
    return data;
};

const chatResponseSchemaResponseTransformer = (data: any) => {
    data.messages = data.messages.map((item: any) => chatMessageWithSchemaTypeSchemaResponseTransformer(item));
    return data;
};

export const aiExampleControllerChatResponseTransformer = async (data: any): Promise<AiExampleControllerChatResponse> => {
    data = chatResponseSchemaResponseTransformer(data);
    return data;
};
