// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * UseCase1SingleGenerationRequest
 *
 * Single generation; trace is finalized with name/output so Langfuse shows them
 */
export type UseCase1SingleGenerationRequest = {
    prompt: string;
    model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    options?: AiGenerateOptions;
};

/**
 * UseCase2GroupedCallsRequest
 *
 * Multiple LLM calls in one request; one trace in Langfuse, finalized at end
 */
export type UseCase2GroupedCallsRequest = {
    /**
     * Prompts for each step (same trace)
     */
    prompts: Array<string>;
    model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
};

/**
 * UseCase3LogicalUnitsRequest
 *
 * Multiple workflows; each workflow gets its own Langfuse trace (split per unit)
 */
export type UseCase3LogicalUnitsRequest = {
    /**
     * One prompt per logical workflow; each gets its own trace
     */
    workflowPrompts: Array<string>;
    model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
};

/**
 * UseCase4ChatSessionRequest
 *
 * Simple generateText with sessionId for grouping traces across requests
 */
export type UseCase4ChatSessionRequest = {
    prompt: string;
    /**
     * Session ID to group traces in Langfuse (e.g. conversation or thread)
     */
    sessionId: string;
    model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
};

/**
 * GenerateTextRequest
 *
 * Request for simple text generation with a single prompt
 */
export type GenerateTextRequest = {
    prompt: string;
    model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    options?: AiGenerateOptions;
};

/**
 * GenerateObjectRequest
 *
 * Request for structured object generation with a predefined schema type
 */
export type GenerateObjectRequest = {
    prompt: string;
    schemaType: 'userProfile' | 'task' | 'product' | 'recipe';
    model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    options?: AiGenerateOptions;
};

/**
 * ChatRequest
 *
 * Request for multi-turn AI conversation with message history. schemaType can be used to request structured output.
 */
export type ChatRequest = {
    messages: Array<ChatMessageWithSchemaType>;
    model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    options?: AiGenerateOptions;
    schemaType?: ChatSchemaType;
};

/**
 * StreamTextRequest
 *
 * Request for streaming text generation with a single prompt
 */
export type StreamTextRequest = {
    prompt: string;
    model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    options?: AiGenerateOptions;
};

/**
 * StreamObjectRequest
 *
 * Request for streaming structured object generation
 */
export type StreamObjectRequest = {
    prompt: string;
    schemaType: 'userProfile' | 'task' | 'product' | 'recipe';
    model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    options?: AiGenerateOptions;
};

/**
 * StreamChatRequest
 *
 * Request for streaming multi-turn AI conversation
 */
export type StreamChatRequest = {
    messages: Array<ChatMessageWithSchemaType>;
    model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    options?: AiGenerateOptions;
};

/**
 * CreateCommentSchema
 *
 * Schema for creating a comment
 */
export type CreateCommentSchema = {
    content: string;
    parentId?: string;
};

/**
 * CreatePostSchema
 *
 * Schema for creating/updating a post
 */
export type CreatePostSchema = {
    title: string;
    content: Array<PostContentSchema>;
    coverImage?: string;
    tags?: Array<string>;
};

/**
 * UpdatePostSchema
 *
 * Schema for updating a post
 */
export type UpdatePostSchema = {
    title?: string;
    content?: Array<PostContentSchema>;
    coverImage?: string;
    tags?: Array<string>;
};

/**
 * GenerateTextResponse
 *
 * Response from text generation
 */
export type GenerateTextResponse = {
    usage?: TokenUsage;
    finishReason?: string;
    toolCalls?: Array<ToolCall>;
    toolResults?: Array<ToolResult>;
    result: string;
};

/**
 * TokenUsage
 *
 * Token usage information for an AI generation
 */
export type TokenUsage = {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
};

/**
 * ToolCall
 *
 * A tool call made by the AI
 */
export type ToolCall = {
    toolCallId: string;
    toolName: string;
    args: {
        [key: string]: unknown;
    };
};

/**
 * ToolResult
 *
 * The result of a tool call
 */
export type ToolResult = {
    toolCallId: string;
    toolName: string;
    result: unknown;
};

/**
 * UseCase2GroupedCallsResponse
 *
 * Combined results from grouped LLM calls
 */
export type UseCase2GroupedCallsResponse = {
    traceName: string;
    results: Array<string>;
    usage?: TokenUsage;
};

/**
 * UseCase3LogicalUnitsResponse
 *
 * One result per workflow (each in its own trace)
 */
export type UseCase3LogicalUnitsResponse = {
    workflows: Array<{
        index: number;
        result: string;
        usage?: TokenUsage;
    }>;
};

/**
 * GenerateObjectResponse
 *
 * Response from structured object generation
 */
export type GenerateObjectResponse = {
    usage?: TokenUsage;
    finishReason?: string;
    toolCalls?: Array<ToolCall>;
    toolResults?: Array<ToolResult>;
    result: unknown;
};

/**
 * ChatResponse
 *
 * Response from AI chat conversation
 */
export type ChatResponse = {
    usage?: TokenUsage;
    finishReason?: string;
    toolCalls?: Array<ToolCall>;
    toolResults?: Array<ToolResult>;
    result: string;
    messages: Array<ChatMessageWithSchemaType>;
};

/**
 * ChatMessageWithSchemaType
 *
 * A message with optional schemaType metadata for identifying structured output
 */
export type ChatMessageWithSchemaType = {
    role: 'user' | 'assistant' | 'system' | 'tool';
    content: string;
    metadata?: {
        isConsideredSystemMessage?: boolean;
        /**
         * TokenUsage
         *
         * Total token usage for the message, including tools calls and reasoning steps
         */
        usage?: {
            promptTokens: number;
            completionTokens: number;
            totalTokens: number;
        };
        finishReason?: string;
        /**
         * ISO 8601 timestamp when the message was created
         */
        timestamp?: Date;
        /**
         * Tool calls made to generate the message
         */
        toolCalls?: Array<{
            toolCallId: string;
            toolName: string;
            args: {
                [key: string]: unknown;
            };
        }>;
        /**
         * Reasoning text for the message
         */
        reasonning?: string;
        /**
         * ChatSchemaType
         *
         * Predefined schema types for testing structured output
         */
        schemaType?: 'userProfile' | 'task' | 'product' | 'recipe' | 'none';
    };
};

/**
 * ChatSchemaType
 *
 * Predefined schema types for testing structured output
 */
export const ChatSchemaType = {
    USER_PROFILE: 'userProfile',
    TASK: 'task',
    PRODUCT: 'product',
    RECIPE: 'recipe',
    NONE: 'none'
} as const;

/**
 * ChatSchemaType
 *
 * Predefined schema types for testing structured output
 */
export type ChatSchemaType = typeof ChatSchemaType[keyof typeof ChatSchemaType];

/**
 * CommentSchema
 *
 * Schema for a comment
 */
export type CommentSchema = {
    id: string;
    content: string;
    authorName: string | null;
    createdAt: string;
    user: {
        id: string;
        name: string;
    } | null;
    parentId: string | null;
    replyIds?: Array<string>;
    replyCount?: number;
};

/**
 * CommentsSchema
 *
 * Schema for a paginated list of comments
 */
export type CommentsSchema = {
    data: Array<CommentSchema>;
    meta: {
        offset: number;
        pageSize: number;
        itemCount: number;
        hasMore: boolean;
    };
};

/**
 * UserPostSchema
 *
 * Schema for a user's post
 */
export type UserPostSchema = {
    id: string;
    slug?: string | null;
    title: string;
    content: Array<PostContentSchema>;
    versions: Array<PostVersionSchema>;
    publishedAt?: string | null;
    type: 'published' | 'draft';
    commentCount?: number;
    coverImage?: string;
    tags: Array<TagSchema>;
};

/**
 * PostContentSchema
 *
 * Schema for content items (text, image, video)
 */
export type PostContentSchema = {
    type: 'text';
    data: string;
} | {
    type: 'image';
    data: string;
} | {
    type: 'video';
    data: string;
};

/**
 * PostVersionSchema
 *
 * Schema for a post version
 */
export type PostVersionSchema = {
    id: string;
    title: string;
    createdAt: string;
};

/**
 * TagSchema
 *
 * A tag attached to a post
 */
export type TagSchema = {
    id: string;
    name: string;
    slug: string;
};

/**
 * UserPostsSchema
 *
 * Schema for a list of user's posts
 */
export type UserPostsSchema = {
    data: Array<{
        id: string;
        slug?: string | null;
        title: string;
        versions: Array<PostVersionSchema>;
        publishedAt?: string | null;
        type: 'published' | 'draft';
        commentCount?: number;
        coverImage?: string;
        tags: Array<TagSchema>;
        contentPreview: PostContentSchema;
    }>;
    meta: {
        offset: number;
        pageSize: number;
        itemCount: number;
        hasMore: boolean;
    };
};

/**
 * PublicPostSchema
 *
 * A public post
 */
export type PublicPostSchema = {
    title: string;
    author: {
        name: string;
    };
    content: Array<PostContentSchema>;
    publishedAt: string;
    slug?: string;
    commentCount?: number;
    coverImage?: string;
    likesCount: number;
    tags: Array<TagSchema>;
};

/**
 * PublicPostsSchema
 *
 * A list of public posts
 */
export type PublicPostsSchema = {
    data: Array<{
        title: string;
        author: {
            name: string;
        };
        publishedAt: string;
        slug?: string;
        commentCount?: number;
        coverImage?: string;
        likesCount: number;
        tags: Array<TagSchema>;
        contentPreview: PostContentSchema;
    }>;
    meta: {
        offset: number;
        pageSize: number;
        itemCount: number;
        hasMore: boolean;
    };
};

/**
 * PublicAuthorPostsSchema
 *
 * A list of posts from a specific author
 */
export type PublicAuthorPostsSchema = {
    data: Array<{
        title: string;
        author: {
            name: string;
        };
        publishedAt: string;
        slug?: string;
        commentCount?: number;
        coverImage?: string;
        likesCount: number;
        tags: Array<TagSchema>;
        contentPreview: PostContentSchema;
    }>;
    meta: {
        offset: number;
        pageSize: number;
        itemCount: number;
        hasMore: boolean;
    };
};

/**
 * AiCoreMessage
 *
 * A message in the conversation history following Vercel AI SDK patterns
 */
export type AiCoreMessage = {
    role: 'user' | 'assistant' | 'system' | 'tool';
    content: string;
    metadata?: {
        isConsideredSystemMessage?: boolean;
        usage?: TokenUsage;
        finishReason?: string;
        /**
         * ISO 8601 timestamp when the message was created
         */
        timestamp?: Date;
        /**
         * Tool calls made to generate the message
         */
        toolCalls?: Array<ToolCall>;
        /**
         * Reasoning text for the message
         */
        reasonning?: string;
    };
};

/**
 * AiStreamEvent
 *
 * SSE event for AI text streaming with tool support
 */
export type AiStreamEvent = {
    type: 'chunk';
    text: string;
} | {
    type: 'tool-call';
    toolCallId: string;
    toolName: string;
    args: {
        [key: string]: unknown;
    };
} | {
    type: 'tool-result';
    toolCallId: string;
    toolName: string;
    result: unknown;
} | {
    type: 'done';
    fullText: string;
    /**
     * AiStreamUsage
     *
     * Token usage information for the stream
     */
    usage?: {
        promptTokens: number;
        completionTokens: number;
        totalTokens: number;
    };
    finishReason?: string;
} | {
    type: 'error';
    message: string;
};

/**
 * Task
 *
 * A task
 */
export type Task = {
    title: string;
    description: string;
    priority: 'low' | 'medium' | 'high';
    dueDate?: string;
    tags?: Array<string>;
};

/**
 * Product
 *
 * A product
 */
export type Product = {
    name: string;
    price: number;
    description: string;
    category: string;
    inStock: boolean;
    features?: Array<string>;
};

/**
 * Recipe
 *
 * A recipe
 */
export type Recipe = {
    name: string;
    description: string;
    prepTime: string;
    cookTime: string;
    servings: number;
    difficulty: 'easy' | 'medium' | 'hard';
    ingredients: Array<{
        name: string;
        quantity: string;
    }>;
    instructions: Array<string>;
    tips?: Array<string>;
};

/**
 * UserProfile
 *
 * A user profile
 */
export type UserProfile = {
    name: string;
    age: number;
    email: string;
    bio?: string;
    skills?: Array<string>;
};

/**
 * AiGenerateOptions
 *
 * Options for an AI generation
 */
export type AiGenerateOptions = {
    temperature?: number;
    maxTokens?: number;
    topP?: number;
    frequencyPenalty?: number;
    presencePenalty?: number;
    maxSteps?: number;
    stopWhen?: number;
    telemetry?: {
        /**
         * Trace strategy. Use "inherit" to keep the active OTEL trace, or "split" to create a new (Langfuse) trace for this LLM call.
         */
        traceMode?: 'inherit' | 'split';
        /**
         * Optional explicit (Langfuse) trace ID for split mode. Reuse the same value to group multiple LLM calls in one (Langfuse) trace.
         */
        traceId?: string;
        /**
         * Display name used as root span name for the Langfuse trace. This does not control grouping.
         */
        traceName?: string;
        /**
         * Name for the LLM span. This is forwarded to Vercel telemetry as functionId.
         */
        spanName?: string;
        /**
         * Optional Langfuse session identifier to group related (Langfuse) traces (e.g. chat thread or job run).
         */
        sessionId?: string;
        /**
         * Telemetry metadata attached to (Langfuse) trace/span.
         */
        metadata?: {
            [key: string]: unknown;
        };
        /**
         * The original prompt that was used to generate the response. (Use prompt.toJSON())
         */
        langfuseOriginalPrompt?: string;
    };
    metadata?: {
        [key: string]: unknown;
    };
};

/**
 * PaginationQuerySchema
 *
 * Schema for pagination query
 */
export type PaginationQuerySchema = {
    /**
     * Starting position of the query
     */
    offset: number;
    /**
     * Number of items to return
     */
    pageSize: number;
};

/**
 * SortingQueryStringSchema
 *
 * Schema for sorting items
 */
export type SortingQueryStringSchema = string;

/**
 * FilterQueryStringSchema
 *
 * Filtering query string, in the format of "property:rule[:value];property:rule[:value];..."
 * <br> Available rules: eq, neq, gt, gte, lt, lte, like, nlike, in, nin, isnull, isnotnull
 * <br> Available properties: title, tag
 */
export type FilterQueryStringSchema = string;

export type CommentsControllerPostSlug = string;

export type CommentsControllerGetCommentsFilterItem = {
    property: 'content';
    rule: 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'like' | 'nlike' | 'in' | 'nin' | 'isnull' | 'isnotnull';
    value?: string;
};

export type CommentsControllerGetCommentsFilterArray = Array<CommentsControllerGetCommentsFilterItem>;

export type CommentsControllerGetCommentsSortItem = {
    property: 'createdAt' | 'authorName';
    direction: 'asc' | 'desc';
};

export type CommentsControllerGetCommentsSortArray = Array<CommentsControllerGetCommentsSortItem>;

export type CommentsControllerGetCommentRepliesSortItem = {
    property: 'createdAt' | 'authorName';
    direction: 'asc' | 'desc';
};

export type CommentsControllerGetCommentRepliesSortArray = Array<CommentsControllerGetCommentRepliesSortItem>;

export type PostControllerGetUserPostsFilterItem = {
    property: 'title' | 'tag';
    rule: 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'like' | 'nlike' | 'in' | 'nin' | 'isnull' | 'isnotnull';
    value?: string;
};

export type PostControllerGetUserPostsFilterArray = Array<PostControllerGetUserPostsFilterItem>;

export type PostControllerGetUserPostsSortItem = {
    property: 'title' | 'createdAt';
    direction: 'asc' | 'desc';
};

export type PostControllerGetUserPostsSortArray = Array<PostControllerGetUserPostsSortItem>;

export type PublicPostControllerGetPostsFilterItem = {
    property: 'title' | 'tag';
    rule: 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'like' | 'nlike' | 'in' | 'nin' | 'isnull' | 'isnotnull';
    value?: string;
};

export type PublicPostControllerGetPostsFilterArray = Array<PublicPostControllerGetPostsFilterItem>;

export type PublicPostControllerGetPostsSortItem = {
    property: 'title' | 'createdAt';
    direction: 'asc' | 'desc';
};

export type PublicPostControllerGetPostsSortArray = Array<PublicPostControllerGetPostsSortItem>;

export type PublicAuthorControllerGetAuthorPostsSortItem = {
    property: 'title' | 'createdAt';
    direction: 'asc' | 'desc';
};

export type PublicAuthorControllerGetAuthorPostsSortArray = Array<PublicAuthorControllerGetAuthorPostsSortItem>;

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type CommentsControllerGetCommentsData = {
    body?: never;
    path: {
        postSlug: string;
    };
    query: {
        /**
         * Filtering query string, in the format of "property:rule[:value];property:rule[:value];..."
         * <br> Available rules: eq, neq, gt, gte, lt, lte, like, nlike, in, nin, isnull, isnotnull
         * <br> Available properties: content
         */
        filter?: CommentsControllerGetCommentsFilterArray;
        /**
         * Schema for sorting items
         */
        sort?: CommentsControllerGetCommentsSortArray;
        /**
         * Starting position of the query
         */
        offset: number;
        /**
         * Number of items to return
         */
        pageSize: number;
    };
    url: '/api/posts/{postSlug}/comments';
};

export type CommentsControllerGetCommentsResponses = {
    /**
     * Schema for a paginated list of comments
     */
    200: CommentsSchema;
};

export type CommentsControllerGetCommentsResponse = CommentsControllerGetCommentsResponses[keyof CommentsControllerGetCommentsResponses];

export type CommentsControllerCreateCommentData = {
    /**
     * CreateCommentSchema
     *
     * Schema for creating a comment
     */
    body: {
        content: string;
        parentId?: string;
    };
    path: {
        postSlug: string;
    };
    query?: never;
    url: '/api/posts/{postSlug}/comments';
};

export type CommentsControllerCreateCommentResponses = {
    /**
     * Schema for a comment
     */
    200: CommentSchema;
};

export type CommentsControllerCreateCommentResponse = CommentsControllerCreateCommentResponses[keyof CommentsControllerCreateCommentResponses];

export type CommentsControllerGetCommentCountData = {
    body?: never;
    path: {
        postSlug: string;
    };
    query?: never;
    url: '/api/posts/{postSlug}/comments/count';
};

export type CommentsControllerGetCommentCountResponses = {
    200: unknown;
};

export type CommentsControllerGetCommentRepliesData = {
    body?: never;
    path: {
        commentId: string;
        postSlug: string;
    };
    query: {
        /**
         * Schema for sorting items
         */
        sort?: CommentsControllerGetCommentRepliesSortArray;
        /**
         * Starting position of the query
         */
        offset: number;
        /**
         * Number of items to return
         */
        pageSize: number;
    };
    url: '/api/posts/{postSlug}/comments/{commentId}/replies';
};

export type CommentsControllerGetCommentRepliesResponses = {
    /**
     * Schema for a paginated list of comments
     */
    200: CommentsSchema;
};

export type CommentsControllerGetCommentRepliesResponse = CommentsControllerGetCommentRepliesResponses[keyof CommentsControllerGetCommentRepliesResponses];

export type CommentsControllerDeleteCommentData = {
    body?: never;
    path: {
        commentId: string;
        postSlug: string;
    };
    query?: never;
    url: '/api/posts/{postSlug}/comments/{commentId}';
};

export type CommentsControllerDeleteCommentResponses = {
    200: unknown;
};

export type PostControllerGetUserPostsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Filtering query string, in the format of "property:rule[:value];property:rule[:value];..."
         * <br> Available rules: eq, neq, gt, gte, lt, lte, like, nlike, in, nin, isnull, isnotnull
         * <br> Available properties: title, tag
         */
        filter?: PostControllerGetUserPostsFilterArray;
        /**
         * Schema for sorting items
         */
        sort?: PostControllerGetUserPostsSortArray;
        /**
         * Starting position of the query
         */
        offset: number;
        /**
         * Number of items to return
         */
        pageSize: number;
    };
    url: '/api/admin/posts';
};

export type PostControllerGetUserPostsResponses = {
    /**
     * Schema for a list of user's posts
     */
    200: UserPostsSchema;
};

export type PostControllerGetUserPostsResponse = PostControllerGetUserPostsResponses[keyof PostControllerGetUserPostsResponses];

export type PostControllerCreatePostData = {
    /**
     * CreatePostSchema
     *
     * Schema for creating/updating a post
     */
    body: {
        title: string;
        /**
         * PostContentSchema
         *
         * Schema for content items (text, image, video)
         */
        content: Array<{
            type: 'text';
            data: string;
        } | {
            type: 'image';
            data: string;
        } | {
            type: 'video';
            data: string;
        }>;
        coverImage?: string;
        tags?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/admin/posts';
};

export type PostControllerCreatePostResponses = {
    /**
     * Schema for a user's post
     */
    200: UserPostSchema;
};

export type PostControllerCreatePostResponse = PostControllerCreatePostResponses[keyof PostControllerCreatePostResponses];

export type PostControllerGetUserPostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/posts/{id}';
};

export type PostControllerGetUserPostResponses = {
    /**
     * Schema for a user's post
     */
    200: UserPostSchema;
};

export type PostControllerGetUserPostResponse = PostControllerGetUserPostResponses[keyof PostControllerGetUserPostResponses];

export type PostControllerUpdatePostData = {
    /**
     * UpdatePostSchema
     *
     * Schema for updating a post
     */
    body: {
        title?: string;
        /**
         * PostContentSchema
         *
         * Schema for content items (text, image, video)
         */
        content?: Array<{
            type: 'text';
            data: string;
        } | {
            type: 'image';
            data: string;
        } | {
            type: 'video';
            data: string;
        }>;
        coverImage?: string;
        tags?: Array<string>;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/posts/{id}';
};

export type PostControllerUpdatePostResponses = {
    /**
     * Schema for a user's post
     */
    200: UserPostSchema;
};

export type PostControllerUpdatePostResponse = PostControllerUpdatePostResponses[keyof PostControllerUpdatePostResponses];

export type PostControllerPublishPostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/posts/{id}/publish';
};

export type PostControllerPublishPostResponses = {
    200: unknown;
};

export type PostControllerUnpublishPostData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/admin/posts/{id}/unpublish';
};

export type PostControllerUnpublishPostResponses = {
    200: unknown;
};

export type PublicPostControllerGetRandomPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/posts/random';
};

export type PublicPostControllerGetRandomPostResponses = {
    /**
     * A public post
     */
    200: PublicPostSchema;
};

export type PublicPostControllerGetRandomPostResponse = PublicPostControllerGetRandomPostResponses[keyof PublicPostControllerGetRandomPostResponses];

export type PublicPostControllerGetPostData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/public/posts/{slug}';
};

export type PublicPostControllerGetPostResponses = {
    /**
     * A public post
     */
    200: PublicPostSchema;
};

export type PublicPostControllerGetPostResponse = PublicPostControllerGetPostResponses[keyof PublicPostControllerGetPostResponses];

export type PublicPostControllerGetPostsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Filtering query string, in the format of "property:rule[:value];property:rule[:value];..."
         * <br> Available rules: eq, neq, gt, gte, lt, lte, like, nlike, in, nin, isnull, isnotnull
         * <br> Available properties: title, tag
         */
        filter?: PublicPostControllerGetPostsFilterArray;
        /**
         * Schema for sorting items
         */
        sort?: PublicPostControllerGetPostsSortArray;
        /**
         * Starting position of the query
         */
        offset: number;
        /**
         * Number of items to return
         */
        pageSize: number;
    };
    url: '/api/public/posts';
};

export type PublicPostControllerGetPostsResponses = {
    /**
     * A list of public posts
     */
    200: PublicPostsSchema;
};

export type PublicPostControllerGetPostsResponse = PublicPostControllerGetPostsResponses[keyof PublicPostControllerGetPostsResponses];

export type PublicPostControllerLikePostData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/public/posts/{slug}/like';
};

export type PublicPostControllerLikePostResponses = {
    /**
     * A public post
     */
    200: PublicPostSchema;
};

export type PublicPostControllerLikePostResponse = PublicPostControllerLikePostResponses[keyof PublicPostControllerLikePostResponses];

export type PublicAuthorControllerGetAuthorPostsData = {
    body?: never;
    path: {
        slug: string;
    };
    query: {
        /**
         * Schema for sorting items
         */
        sort?: PublicAuthorControllerGetAuthorPostsSortArray;
        /**
         * Starting position of the query
         */
        offset: number;
        /**
         * Number of items to return
         */
        pageSize: number;
    };
    url: '/api/public/authors/{slug}/posts';
};

export type PublicAuthorControllerGetAuthorPostsResponses = {
    /**
     * A list of posts from a specific author
     */
    200: PublicAuthorPostsSchema;
};

export type PublicAuthorControllerGetAuthorPostsResponse = PublicAuthorControllerGetAuthorPostsResponses[keyof PublicAuthorControllerGetAuthorPostsResponses];

export type AiExampleControllerGenerateTextData = {
    /**
     * GenerateTextRequest
     *
     * Request for simple text generation with a single prompt
     */
    body: {
        prompt: string;
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
        /**
         * AiGenerateOptions
         *
         * Options for an AI generation
         */
        options?: {
            temperature?: number;
            maxTokens?: number;
            topP?: number;
            frequencyPenalty?: number;
            presencePenalty?: number;
            maxSteps?: number;
            stopWhen?: number;
            telemetry?: {
                /**
                 * Trace strategy. Use "inherit" to keep the active OTEL trace, or "split" to create a new (Langfuse) trace for this LLM call.
                 */
                traceMode?: 'inherit' | 'split';
                /**
                 * Optional explicit (Langfuse) trace ID for split mode. Reuse the same value to group multiple LLM calls in one (Langfuse) trace.
                 */
                traceId?: string;
                /**
                 * Display name used as root span name for the Langfuse trace. This does not control grouping.
                 */
                traceName?: string;
                /**
                 * Name for the LLM span. This is forwarded to Vercel telemetry as functionId.
                 */
                spanName?: string;
                /**
                 * Optional Langfuse session identifier to group related (Langfuse) traces (e.g. chat thread or job run).
                 */
                sessionId?: string;
                /**
                 * Telemetry metadata attached to (Langfuse) trace/span.
                 */
                metadata?: {
                    [key: string]: unknown;
                };
                /**
                 * The original prompt that was used to generate the response. (Use prompt.toJSON())
                 */
                langfuseOriginalPrompt?: string;
            };
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
    path?: never;
    query?: never;
    url: '/api/ai/generate-text';
};

export type AiExampleControllerGenerateTextResponses = {
    /**
     * Response from text generation
     */
    200: GenerateTextResponse;
};

export type AiExampleControllerGenerateTextResponse = AiExampleControllerGenerateTextResponses[keyof AiExampleControllerGenerateTextResponses];

export type AiExampleControllerGenerateObjectData = {
    /**
     * GenerateObjectRequest
     *
     * Request for structured object generation with a predefined schema type
     */
    body: {
        prompt: string;
        schemaType: 'userProfile' | 'task' | 'product' | 'recipe';
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
        /**
         * AiGenerateOptions
         *
         * Options for an AI generation
         */
        options?: {
            temperature?: number;
            maxTokens?: number;
            topP?: number;
            frequencyPenalty?: number;
            presencePenalty?: number;
            maxSteps?: number;
            stopWhen?: number;
            telemetry?: {
                /**
                 * Trace strategy. Use "inherit" to keep the active OTEL trace, or "split" to create a new (Langfuse) trace for this LLM call.
                 */
                traceMode?: 'inherit' | 'split';
                /**
                 * Optional explicit (Langfuse) trace ID for split mode. Reuse the same value to group multiple LLM calls in one (Langfuse) trace.
                 */
                traceId?: string;
                /**
                 * Display name used as root span name for the Langfuse trace. This does not control grouping.
                 */
                traceName?: string;
                /**
                 * Name for the LLM span. This is forwarded to Vercel telemetry as functionId.
                 */
                spanName?: string;
                /**
                 * Optional Langfuse session identifier to group related (Langfuse) traces (e.g. chat thread or job run).
                 */
                sessionId?: string;
                /**
                 * Telemetry metadata attached to (Langfuse) trace/span.
                 */
                metadata?: {
                    [key: string]: unknown;
                };
                /**
                 * The original prompt that was used to generate the response. (Use prompt.toJSON())
                 */
                langfuseOriginalPrompt?: string;
            };
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
    path?: never;
    query?: never;
    url: '/api/ai/generate-object';
};

export type AiExampleControllerGenerateObjectResponses = {
    /**
     * Response from structured object generation
     */
    200: GenerateObjectResponse;
};

export type AiExampleControllerGenerateObjectResponse = AiExampleControllerGenerateObjectResponses[keyof AiExampleControllerGenerateObjectResponses];

export type AiExampleControllerChatData = {
    /**
     * ChatRequest
     *
     * Request for multi-turn AI conversation with message history. schemaType can be used to request structured output.
     */
    body: {
        messages: Array<{
            role: 'user' | 'assistant' | 'system' | 'tool';
            content: string;
            metadata?: {
                isConsideredSystemMessage?: boolean;
                /**
                 * TokenUsage
                 *
                 * Total token usage for the message, including tools calls and reasoning steps
                 */
                usage?: {
                    promptTokens: number;
                    completionTokens: number;
                    totalTokens: number;
                };
                finishReason?: string;
                /**
                 * ISO 8601 timestamp when the message was created
                 */
                timestamp?: Date;
                /**
                 * Tool calls made to generate the message
                 */
                toolCalls?: Array<{
                    toolCallId: string;
                    toolName: string;
                    args: {
                        [key: string]: unknown;
                    };
                }>;
                /**
                 * Reasoning text for the message
                 */
                reasonning?: string;
                /**
                 * ChatSchemaType
                 *
                 * Predefined schema types for testing structured output
                 */
                schemaType?: 'userProfile' | 'task' | 'product' | 'recipe' | 'none';
            };
        }>;
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
        /**
         * AiGenerateOptions
         *
         * Options for an AI generation
         */
        options?: {
            temperature?: number;
            maxTokens?: number;
            topP?: number;
            frequencyPenalty?: number;
            presencePenalty?: number;
            maxSteps?: number;
            stopWhen?: number;
            telemetry?: {
                /**
                 * Trace strategy. Use "inherit" to keep the active OTEL trace, or "split" to create a new (Langfuse) trace for this LLM call.
                 */
                traceMode?: 'inherit' | 'split';
                /**
                 * Optional explicit (Langfuse) trace ID for split mode. Reuse the same value to group multiple LLM calls in one (Langfuse) trace.
                 */
                traceId?: string;
                /**
                 * Display name used as root span name for the Langfuse trace. This does not control grouping.
                 */
                traceName?: string;
                /**
                 * Name for the LLM span. This is forwarded to Vercel telemetry as functionId.
                 */
                spanName?: string;
                /**
                 * Optional Langfuse session identifier to group related (Langfuse) traces (e.g. chat thread or job run).
                 */
                sessionId?: string;
                /**
                 * Telemetry metadata attached to (Langfuse) trace/span.
                 */
                metadata?: {
                    [key: string]: unknown;
                };
                /**
                 * The original prompt that was used to generate the response. (Use prompt.toJSON())
                 */
                langfuseOriginalPrompt?: string;
            };
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * ChatSchemaType
         *
         * Predefined schema types for testing structured output
         */
        schemaType?: 'userProfile' | 'task' | 'product' | 'recipe' | 'none';
    };
    path?: never;
    query?: never;
    url: '/api/ai/chat';
};

export type AiExampleControllerChatResponses = {
    /**
     * Response from AI chat conversation
     */
    200: ChatResponse;
};

export type AiExampleControllerChatResponse = AiExampleControllerChatResponses[keyof AiExampleControllerChatResponses];

export type AiExampleControllerStreamTextData = {
    /**
     * StreamTextRequest
     *
     * Request for streaming text generation with a single prompt
     */
    body: {
        prompt: string;
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
        /**
         * AiGenerateOptions
         *
         * Options for an AI generation
         */
        options?: {
            temperature?: number;
            maxTokens?: number;
            topP?: number;
            frequencyPenalty?: number;
            presencePenalty?: number;
            maxSteps?: number;
            stopWhen?: number;
            telemetry?: {
                /**
                 * Trace strategy. Use "inherit" to keep the active OTEL trace, or "split" to create a new (Langfuse) trace for this LLM call.
                 */
                traceMode?: 'inherit' | 'split';
                /**
                 * Optional explicit (Langfuse) trace ID for split mode. Reuse the same value to group multiple LLM calls in one (Langfuse) trace.
                 */
                traceId?: string;
                /**
                 * Display name used as root span name for the Langfuse trace. This does not control grouping.
                 */
                traceName?: string;
                /**
                 * Name for the LLM span. This is forwarded to Vercel telemetry as functionId.
                 */
                spanName?: string;
                /**
                 * Optional Langfuse session identifier to group related (Langfuse) traces (e.g. chat thread or job run).
                 */
                sessionId?: string;
                /**
                 * Telemetry metadata attached to (Langfuse) trace/span.
                 */
                metadata?: {
                    [key: string]: unknown;
                };
                /**
                 * The original prompt that was used to generate the response. (Use prompt.toJSON())
                 */
                langfuseOriginalPrompt?: string;
            };
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
    path?: never;
    query?: never;
    url: '/api/ai/stream-text';
};

export type AiExampleControllerStreamTextResponses = {
    201: unknown;
};

export type AiExampleControllerStreamObjectData = {
    /**
     * StreamObjectRequest
     *
     * Request for streaming structured object generation
     */
    body: {
        prompt: string;
        schemaType: 'userProfile' | 'task' | 'product' | 'recipe';
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
        /**
         * AiGenerateOptions
         *
         * Options for an AI generation
         */
        options?: {
            temperature?: number;
            maxTokens?: number;
            topP?: number;
            frequencyPenalty?: number;
            presencePenalty?: number;
            maxSteps?: number;
            stopWhen?: number;
            telemetry?: {
                /**
                 * Trace strategy. Use "inherit" to keep the active OTEL trace, or "split" to create a new (Langfuse) trace for this LLM call.
                 */
                traceMode?: 'inherit' | 'split';
                /**
                 * Optional explicit (Langfuse) trace ID for split mode. Reuse the same value to group multiple LLM calls in one (Langfuse) trace.
                 */
                traceId?: string;
                /**
                 * Display name used as root span name for the Langfuse trace. This does not control grouping.
                 */
                traceName?: string;
                /**
                 * Name for the LLM span. This is forwarded to Vercel telemetry as functionId.
                 */
                spanName?: string;
                /**
                 * Optional Langfuse session identifier to group related (Langfuse) traces (e.g. chat thread or job run).
                 */
                sessionId?: string;
                /**
                 * Telemetry metadata attached to (Langfuse) trace/span.
                 */
                metadata?: {
                    [key: string]: unknown;
                };
                /**
                 * The original prompt that was used to generate the response. (Use prompt.toJSON())
                 */
                langfuseOriginalPrompt?: string;
            };
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
    path?: never;
    query?: never;
    url: '/api/ai/stream-object';
};

export type AiExampleControllerStreamObjectResponses = {
    201: unknown;
};

export type AiExampleControllerStreamChatData = {
    /**
     * StreamChatRequest
     *
     * Request for streaming multi-turn AI conversation
     */
    body: {
        messages: Array<{
            role: 'user' | 'assistant' | 'system' | 'tool';
            content: string;
            metadata?: {
                isConsideredSystemMessage?: boolean;
                /**
                 * TokenUsage
                 *
                 * Total token usage for the message, including tools calls and reasoning steps
                 */
                usage?: {
                    promptTokens: number;
                    completionTokens: number;
                    totalTokens: number;
                };
                finishReason?: string;
                /**
                 * ISO 8601 timestamp when the message was created
                 */
                timestamp?: Date;
                /**
                 * Tool calls made to generate the message
                 */
                toolCalls?: Array<{
                    toolCallId: string;
                    toolName: string;
                    args: {
                        [key: string]: unknown;
                    };
                }>;
                /**
                 * Reasoning text for the message
                 */
                reasonning?: string;
                /**
                 * ChatSchemaType
                 *
                 * Predefined schema types for testing structured output
                 */
                schemaType?: 'userProfile' | 'task' | 'product' | 'recipe' | 'none';
            };
        }>;
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
        /**
         * AiGenerateOptions
         *
         * Options for an AI generation
         */
        options?: {
            temperature?: number;
            maxTokens?: number;
            topP?: number;
            frequencyPenalty?: number;
            presencePenalty?: number;
            maxSteps?: number;
            stopWhen?: number;
            telemetry?: {
                /**
                 * Trace strategy. Use "inherit" to keep the active OTEL trace, or "split" to create a new (Langfuse) trace for this LLM call.
                 */
                traceMode?: 'inherit' | 'split';
                /**
                 * Optional explicit (Langfuse) trace ID for split mode. Reuse the same value to group multiple LLM calls in one (Langfuse) trace.
                 */
                traceId?: string;
                /**
                 * Display name used as root span name for the Langfuse trace. This does not control grouping.
                 */
                traceName?: string;
                /**
                 * Name for the LLM span. This is forwarded to Vercel telemetry as functionId.
                 */
                spanName?: string;
                /**
                 * Optional Langfuse session identifier to group related (Langfuse) traces (e.g. chat thread or job run).
                 */
                sessionId?: string;
                /**
                 * Telemetry metadata attached to (Langfuse) trace/span.
                 */
                metadata?: {
                    [key: string]: unknown;
                };
                /**
                 * The original prompt that was used to generate the response. (Use prompt.toJSON())
                 */
                langfuseOriginalPrompt?: string;
            };
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
    path?: never;
    query?: never;
    url: '/api/ai/stream-chat';
};

export type AiExampleControllerStreamChatResponses = {
    201: unknown;
};

export type AiExampleUseCasesControllerUseCase1SingleGenerationData = {
    /**
     * UseCase1SingleGenerationRequest
     *
     * Single generation; trace is finalized with name/output so Langfuse shows them
     */
    body: {
        prompt: string;
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
        /**
         * AiGenerateOptions
         *
         * Options for an AI generation
         */
        options?: {
            temperature?: number;
            maxTokens?: number;
            topP?: number;
            frequencyPenalty?: number;
            presencePenalty?: number;
            maxSteps?: number;
            stopWhen?: number;
            telemetry?: {
                /**
                 * Trace strategy. Use "inherit" to keep the active OTEL trace, or "split" to create a new (Langfuse) trace for this LLM call.
                 */
                traceMode?: 'inherit' | 'split';
                /**
                 * Optional explicit (Langfuse) trace ID for split mode. Reuse the same value to group multiple LLM calls in one (Langfuse) trace.
                 */
                traceId?: string;
                /**
                 * Display name used as root span name for the Langfuse trace. This does not control grouping.
                 */
                traceName?: string;
                /**
                 * Name for the LLM span. This is forwarded to Vercel telemetry as functionId.
                 */
                spanName?: string;
                /**
                 * Optional Langfuse session identifier to group related (Langfuse) traces (e.g. chat thread or job run).
                 */
                sessionId?: string;
                /**
                 * Telemetry metadata attached to (Langfuse) trace/span.
                 */
                metadata?: {
                    [key: string]: unknown;
                };
                /**
                 * The original prompt that was used to generate the response. (Use prompt.toJSON())
                 */
                langfuseOriginalPrompt?: string;
            };
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
    path?: never;
    query?: never;
    url: '/api/ai/examples/use-case-1-single-generation';
};

export type AiExampleUseCasesControllerUseCase1SingleGenerationResponses = {
    /**
     * Response from text generation
     */
    200: GenerateTextResponse;
};

export type AiExampleUseCasesControllerUseCase1SingleGenerationResponse = AiExampleUseCasesControllerUseCase1SingleGenerationResponses[keyof AiExampleUseCasesControllerUseCase1SingleGenerationResponses];

export type AiExampleUseCasesControllerUseCase2GroupedCallsData = {
    /**
     * UseCase2GroupedCallsRequest
     *
     * Multiple LLM calls in one request; one trace in Langfuse, finalized at end
     */
    body: {
        /**
         * Prompts for each step (same trace)
         */
        prompts: Array<string>;
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    };
    path?: never;
    query?: never;
    url: '/api/ai/examples/use-case-2-grouped-calls';
};

export type AiExampleUseCasesControllerUseCase2GroupedCallsResponses = {
    /**
     * Combined results from grouped LLM calls
     */
    200: UseCase2GroupedCallsResponse;
};

export type AiExampleUseCasesControllerUseCase2GroupedCallsResponse = AiExampleUseCasesControllerUseCase2GroupedCallsResponses[keyof AiExampleUseCasesControllerUseCase2GroupedCallsResponses];

export type AiExampleUseCasesControllerUseCase3LogicalUnitsData = {
    /**
     * UseCase3LogicalUnitsRequest
     *
     * Multiple workflows; each workflow gets its own Langfuse trace (split per unit)
     */
    body: {
        /**
         * One prompt per logical workflow; each gets its own trace
         */
        workflowPrompts: Array<string>;
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    };
    path?: never;
    query?: never;
    url: '/api/ai/examples/use-case-3-logical-units';
};

export type AiExampleUseCasesControllerUseCase3LogicalUnitsResponses = {
    /**
     * One result per workflow (each in its own trace)
     */
    200: UseCase3LogicalUnitsResponse;
};

export type AiExampleUseCasesControllerUseCase3LogicalUnitsResponse = AiExampleUseCasesControllerUseCase3LogicalUnitsResponses[keyof AiExampleUseCasesControllerUseCase3LogicalUnitsResponses];

export type AiExampleUseCasesControllerUseCase4ChatSessionData = {
    /**
     * UseCase4ChatSessionRequest
     *
     * Simple generateText with sessionId for grouping traces across requests
     */
    body: {
        prompt: string;
        /**
         * Session ID to group traces in Langfuse (e.g. conversation or thread)
         */
        sessionId: string;
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    };
    path?: never;
    query?: never;
    url: '/api/ai/examples/use-case-4-chat-session';
};

export type AiExampleUseCasesControllerUseCase4ChatSessionResponses = {
    /**
     * Response from text generation
     */
    200: GenerateTextResponse;
};

export type AiExampleUseCasesControllerUseCase4ChatSessionResponse = AiExampleUseCasesControllerUseCase4ChatSessionResponses[keyof AiExampleUseCasesControllerUseCase4ChatSessionResponses];

export type AiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedData = {
    /**
     * UseCase4ChatSessionRequest
     *
     * Simple generateText with sessionId for grouping traces across requests
     */
    body: {
        prompt: string;
        /**
         * Session ID to group traces in Langfuse (e.g. conversation or thread)
         */
        sessionId: string;
        model?: 'OPENAI_GPT_5_NANO' | 'GOOGLE_GEMINI_3_FLASH' | 'CLAUDE_HAIKU_3_5' | 'CLAUDE_OPUS_4_5' | 'MISTRAL_SMALL';
    };
    path?: never;
    query?: never;
    url: '/api/ai/examples/use-case-5-chat-session-with-turns-merged';
};

export type AiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedResponses = {
    /**
     * Response from text generation
     */
    200: GenerateTextResponse;
};

export type AiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedResponse = AiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedResponses[keyof AiExampleUseCasesControllerUseCase5ChatSessionWithTurnsMergedResponses];
