// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * CreateReferent
 *
 * Create a referent
 */
export const zCreateReferent = z.object({
    firstName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    lastName: z.string().min(1),
    contactEmail: z.optional(z.union([
        z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        z.null()
    ])),
    contactPhone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    userId: z.optional(z.union([
        z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        z.null()
    ]))
});

/**
 * UpdateReferent
 *
 * Update a referent (send the loaded version)
 */
export const zUpdateReferent = z.object({
    firstName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    lastName: z.optional(z.string().min(1)),
    contactEmail: z.optional(z.union([
        z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        z.null()
    ])),
    contactPhone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    userId: z.optional(z.union([
        z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        z.null()
    ])),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * CreateCategory
 *
 * Create a category
 */
export const zCreateCategory = z.object({
    name: z.string().min(1),
    parentId: z.optional(z.union([
        z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        z.null()
    ]))
});

/**
 * UpdateCategory
 *
 * Rename or reparent a category
 */
export const zUpdateCategory = z.object({
    name: z.optional(z.string().min(1)),
    parentId: z.optional(z.union([
        z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        z.null()
    ])),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * CreateProducerCategory
 *
 * Create a producer category
 */
export const zCreateProducerCategory = z.object({
    name: z.string().min(1)
});

/**
 * UpdateProducerCategory
 *
 * Rename a producer category
 */
export const zUpdateProducerCategory = z.object({
    name: z.optional(z.string().min(1)),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * SetProductPrice
 *
 * Set a new current price; the previous window is closed at effectiveFrom (or now)
 */
export const zSetProductPrice = z.object({
    amountEur: z.number().gt(0),
    effectiveFrom: z.optional(z.string())
});

/**
 * MemberValidation
 *
 * Validate a pending member (moves them to active) or reject them with a reason
 */
export const zMemberValidation = z.union([
    z.object({
        decision: z.literal('validate'),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    z.object({
        decision: z.literal('reject'),
        reason: z.string().min(1),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    })
]);

/**
 * UpdateMemberProfile
 *
 * Update a member’s name and personal details (send the version you loaded)
 */
export const zUpdateMemberProfile = z.object({
    addressLine1: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    addressLine2: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    postalCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    city: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    name: z.optional(z.string().min(2)),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * SetMembershipFee
 *
 * Set the expected membership fee for a member (the "variable fee"). Send the member version you loaded — a stale value returns 409.
 */
export const zSetMembershipFee = z.object({
    expectedAmountCents: z.int().gte(0).lte(9007199254740991),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * TerminateMember
 *
 * Terminate a member with a reason (admin action)
 */
export const zTerminateMember = z.object({
    reason: z.string().min(1),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * ReactivateMember
 *
 * Return a terminated member to active
 */
export const zReactivateMember = z.object({
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * SelfTerminate
 *
 * A member ending their own membership
 */
export const zSelfTerminate = z.object({
    confirm: z.literal(true)
});

/**
 * MembershipIntake
 *
 * Whether self-registration is currently accepted
 */
export const zMembershipIntake = z.object({
    open: z.boolean()
});

/**
 * UpdateCartLine
 *
 * Change a line's quantity
 */
export const zUpdateCartLine = z.object({
    quantity: z.number().gt(0)
});

/**
 * SupplierType
 *
 * Whether the supplier is a producer or a wholesaler
 */
export const zSupplierType = z.enum(['producer', 'wholesaler']);

/**
 * CreateSupplier
 *
 * Create a supplier
 */
export const zCreateSupplier = z.object({
    name: z.string().min(1),
    type: zSupplierType,
    contactName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    contactEmail: z.optional(z.union([
        z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        z.null()
    ])),
    contactPhone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    deliveryMode: z.optional(z.union([
        z.enum(['livraison', 'collecte']),
        z.null()
    ])),
    referentId: z.optional(z.union([
        z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        z.null()
    ])),
    producerCategoryIds: z.optional(z.union([
        z.array(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)),
        z.null()
    ]))
});

/**
 * UpdateSupplier
 *
 * Update a supplier (send the loaded version)
 */
export const zUpdateSupplier = z.object({
    name: z.optional(z.string().min(1)),
    type: z.optional(zSupplierType),
    contactName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    contactEmail: z.optional(z.union([
        z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        z.null()
    ])),
    contactPhone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    deliveryMode: z.optional(z.union([
        z.enum(['livraison', 'collecte']),
        z.null()
    ])),
    referentId: z.optional(z.union([
        z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        z.null()
    ])),
    producerCategoryIds: z.optional(z.union([
        z.array(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)),
        z.null()
    ])),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * CatalogSupplier
 *
 * A source of products
 */
export const zCatalogSupplier = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    type: zSupplierType,
    contactName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    contactEmail: z.optional(z.union([
        z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        z.null()
    ])),
    contactPhone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    notes: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    deliveryMode: z.optional(z.union([
        z.enum(['livraison', 'collecte']),
        z.null()
    ])),
    referent: z.optional(z.union([
        z.object({
            id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            firstName: z.optional(z.union([
                z.string(),
                z.null()
            ])),
            lastName: z.string()
        }),
        z.null()
    ])),
    producerCategories: z.array(z.object({
        id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        name: z.string()
    })),
    archivedAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    productCount: z.int().gte(-9007199254740991).lte(9007199254740991),
    version: z.int().gte(-9007199254740991).lte(9007199254740991),
    createdAt: z.string()
});

/**
 * CatalogSuppliersList
 *
 * A paginated list of suppliers
 */
export const zCatalogSuppliersList = z.object({
    data: z.array(zCatalogSupplier),
    meta: z.object({
        offset: z.number(),
        pageSize: z.number(),
        itemCount: z.number(),
        hasMore: z.boolean()
    })
});

/**
 * CatalogReferent
 *
 * The co-op member who follows a supplier
 */
export const zCatalogReferent = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    firstName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    lastName: z.string(),
    contactEmail: z.optional(z.union([
        z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        z.null()
    ])),
    contactPhone: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    userId: z.optional(z.union([
        z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        z.null()
    ])),
    supplierCount: z.int().gte(-9007199254740991).lte(9007199254740991),
    version: z.int().gte(-9007199254740991).lte(9007199254740991),
    createdAt: z.string()
});

/**
 * CatalogReferentsList
 *
 * All referents
 */
export const zCatalogReferentsList = z.array(zCatalogReferent);

/**
 * CatalogCategory
 *
 * A grouping for products in the catalogue
 */
export const zCatalogCategory = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    parentId: z.optional(z.union([
        z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        z.null()
    ])),
    archivedAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    productCount: z.int().gte(-9007199254740991).lte(9007199254740991),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * CatalogCategoriesList
 *
 * All categories (one nesting level)
 */
export const zCatalogCategoriesList = z.array(zCatalogCategory);

/**
 * CatalogProducerCategory
 *
 * A tag for what a supplier produces (e.g. "Boissons", "Fromages")
 */
export const zCatalogProducerCategory = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    archivedAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    supplierCount: z.int().gte(-9007199254740991).lte(9007199254740991),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * CatalogProducerCategoriesList
 *
 * All producer categories
 */
export const zCatalogProducerCategoriesList = z.array(zCatalogProducerCategory);

/**
 * ProductSaleMode
 *
 * "unit" is sold per piece, "weight" is priced per kilogram
 */
export const zProductSaleMode = z.enum(['unit', 'weight']);

/**
 * ProductPricingUnit
 *
 * Derived from the sale mode: unit → piece, weight → kg
 */
export const zProductPricingUnit = z.enum(['piece', 'kg']);

/**
 * ProductOrderingMode
 *
 * pre_order = ordered ahead from the producer for a future delivery; in_store = bought from what the cooperative currently has on the shelf; both = the member picks one when adding it to their cart
 */
export const zProductOrderingMode = z.enum([
    'pre_order',
    'in_store',
    'both'
]);

/**
 * ProductLabel
 *
 * Informational badges shown on the product
 */
export const zProductLabel = z.enum([
    'organic',
    'local',
    'vegetarian',
    'vegan'
]);

/**
 * CreateProduct
 *
 * Create a catalogue product with its first price. pricingUnit is derived from saleMode.
 */
export const zCreateProduct = z.object({
    name: z.string().min(1),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    supplierId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    categoryId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    saleMode: zProductSaleMode,
    orderingMode: zProductOrderingMode,
    photos: z.array(z.string()).default([]),
    labels: z.array(zProductLabel).default([]),
    barcode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    averageWeightGrams: z.optional(z.union([
        z.int().gt(0).lte(9007199254740991),
        z.null()
    ])),
    weightTolerancePercent: z.optional(z.union([
        z.int().gt(0).lte(9007199254740991),
        z.null()
    ])),
    initialPriceEur: z.number().gt(0)
});

/**
 * UpdateProduct
 *
 * Update a product (not its price)
 */
export const zUpdateProduct = z.object({
    name: z.optional(z.string().min(1)),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    supplierId: z.optional(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)),
    categoryId: z.optional(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)),
    saleMode: z.optional(zProductSaleMode),
    orderingMode: z.optional(zProductOrderingMode),
    photos: z.optional(z.array(z.string())).default([]),
    labels: z.optional(z.array(zProductLabel)).default([]),
    barcode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    averageWeightGrams: z.optional(z.union([
        z.int().gt(0).lte(9007199254740991),
        z.null()
    ])),
    weightTolerancePercent: z.optional(z.union([
        z.int().gt(0).lte(9007199254740991),
        z.null()
    ])),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * CatalogProduct
 *
 * An item the cooperative offers
 */
export const zCatalogProduct = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    supplier: z.object({
        id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        name: z.string()
    }),
    category: z.object({
        id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        name: z.string()
    }),
    saleMode: zProductSaleMode,
    pricingUnit: zProductPricingUnit,
    orderingMode: zProductOrderingMode,
    photos: z.array(z.string()),
    labels: z.array(zProductLabel),
    barcode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    currentPriceEur: z.optional(z.union([
        z.number().gt(0),
        z.null()
    ])),
    archivedAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    version: z.int().gte(-9007199254740991).lte(9007199254740991),
    createdAt: z.string()
});

/**
 * CatalogProductsList
 *
 * A paginated list of products
 */
export const zCatalogProductsList = z.object({
    data: z.array(zCatalogProduct),
    meta: z.object({
        offset: z.number(),
        pageSize: z.number(),
        itemCount: z.number(),
        hasMore: z.boolean()
    })
});

/**
 * CatalogPriceWindow
 *
 * One entry in a product’s price history
 */
export const zCatalogPriceWindow = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    amountEur: z.number().gt(0),
    currency: z.string(),
    validFrom: z.string(),
    validTo: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    setByName: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * CatalogProductDetail
 *
 * A product with its full price history
 */
export const zCatalogProductDetail = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    supplier: z.object({
        id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        name: z.string()
    }),
    category: z.object({
        id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        name: z.string()
    }),
    saleMode: zProductSaleMode,
    pricingUnit: zProductPricingUnit,
    orderingMode: zProductOrderingMode,
    photos: z.array(z.string()),
    labels: z.array(zProductLabel),
    barcode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    currentPriceEur: z.optional(z.union([
        z.number().gt(0),
        z.null()
    ])),
    archivedAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    version: z.int().gte(-9007199254740991).lte(9007199254740991),
    createdAt: z.string(),
    priceHistory: z.array(zCatalogPriceWindow),
    averageWeightGrams: z.optional(z.union([
        z.int().gte(-9007199254740991).lte(9007199254740991),
        z.null()
    ])),
    weightTolerancePercent: z.optional(z.union([
        z.int().gte(-9007199254740991).lte(9007199254740991),
        z.null()
    ]))
});

/**
 * ShopCategory
 *
 * A category with at least one orderable product
 */
export const zShopCategory = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string()
});

/**
 * ShopCategoriesList
 *
 * Categories that currently have at least one orderable product
 */
export const zShopCategoriesList = z.array(zShopCategory);

/**
 * ShopProduct
 *
 * A product as shown in the public shop list
 */
export const zShopProduct = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    category: z.object({
        id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        name: z.string()
    }),
    saleMode: z.enum(['unit', 'weight']),
    pricingUnit: z.enum(['piece', 'kg']),
    photos: z.array(z.string()),
    labels: z.array(z.enum([
        'organic',
        'local',
        'vegetarian',
        'vegan'
    ])),
    currentPriceEur: z.number().gt(0),
    orderingMode: z.enum([
        'pre_order',
        'in_store',
        'both'
    ])
});

/**
 * ShopProductsList
 *
 * A paginated list of orderable products
 */
export const zShopProductsList = z.object({
    data: z.array(zShopProduct),
    meta: z.object({
        offset: z.number(),
        pageSize: z.number(),
        itemCount: z.number(),
        hasMore: z.boolean()
    })
});

/**
 * ShopProductDetail
 *
 * A product detail page shown in the public shop — narrower than the admin detail
 */
export const zShopProductDetail = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    name: z.string(),
    category: z.object({
        id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        name: z.string()
    }),
    saleMode: zProductSaleMode,
    pricingUnit: zProductPricingUnit,
    photos: z.array(z.string()),
    labels: z.array(zProductLabel),
    currentPriceEur: z.number().gt(0),
    orderingMode: zProductOrderingMode,
    description: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    barcode: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * MemberListItem
 *
 * A member as shown in the back-office list
 */
export const zMemberListItem = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    membershipNumber: z.string(),
    name: z.string(),
    email: z.optional(z.union([
        z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        z.null()
    ])),
    phoneNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    status: z.enum([
        'pending',
        'active',
        'rejected',
        'terminated'
    ]),
    roles: z.array(z.enum(['member', 'admin'])),
    feeState: z.enum([
        'unpaid',
        'partly_paid',
        'paid'
    ]),
    createdAt: z.string()
});

/**
 * MembersList
 *
 * A paginated list of members
 */
export const zMembersList = z.object({
    data: z.array(zMemberListItem),
    meta: z.object({
        offset: z.number(),
        pageSize: z.number(),
        itemCount: z.number(),
        hasMore: z.boolean()
    })
});

/**
 * MemberStatus
 *
 * Lifecycle status of a cooperative member
 */
export const zMemberStatus = z.enum([
    'pending',
    'active',
    'rejected',
    'terminated'
]);

/**
 * UserRole
 *
 * Access role. "admin" is a superset of "member". "grocer" is added in lot 4.
 */
export const zUserRole = z.enum(['member', 'admin']);

/**
 * CreateMember
 *
 * An administrator creates a member directly. The person receives no password — they use "forgot password" to set one.
 */
export const zCreateMember = z.object({
    name: z.string().min(2),
    email: z.optional(z.union([
        z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        z.null()
    ])),
    phoneNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    profile: z.optional(z.object({
        addressLine1: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        addressLine2: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        postalCode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        city: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        phone: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    })),
    roles: z.array(zUserRole).min(1).default(['member']),
    status: z.enum(['pending', 'active'])
});

/**
 * SetMemberRoles
 *
 * Replace a member’s access roles. Every member keeps "member"; adding "admin" grants the back office.
 */
export const zSetMemberRoles = z.object({
    roles: z.array(zUserRole).min(1),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * MembershipFeeState
 *
 * Derived from the sum of recorded payments against the expected amount
 */
export const zMembershipFeeState = z.enum([
    'unpaid',
    'partly_paid',
    'paid'
]);

/**
 * MemberIdentifiers
 *
 * The email and/or phone the account signs in with
 */
export const zMemberIdentifiers = z.object({
    email: z.optional(z.union([
        z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
        z.null()
    ])),
    emailVerified: z.boolean(),
    phoneNumber: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phoneNumberVerified: z.boolean()
});

/**
 * MemberProfile
 *
 * A member’s editable personal details
 */
export const zMemberProfile = z.object({
    addressLine1: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    addressLine2: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    postalCode: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    city: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    phone: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * FeeSummary
 *
 * Membership-fee expectation, total paid, and derived state
 */
export const zFeeSummary = z.object({
    expectedAmountCents: z.int().gte(0).lte(9007199254740991),
    paidAmountCents: z.int().gte(-9007199254740991).lte(9007199254740991),
    state: z.enum([
        'unpaid',
        'partly_paid',
        'paid'
    ])
});

/**
 * MemberStatusChange
 *
 * One entry in a member’s status history
 */
export const zMemberStatusChange = z.object({
    fromStatus: z.optional(z.union([
        z.enum([
            'pending',
            'active',
            'rejected',
            'terminated'
        ]),
        z.null()
    ])),
    toStatus: z.enum([
        'pending',
        'active',
        'rejected',
        'terminated'
    ]),
    reason: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    changedByName: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    createdAt: z.string()
});

/**
 * MemberPayment
 *
 * One recorded membership-fee payment or adjustment
 */
export const zMemberPayment = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    kind: z.enum(['payment', 'adjustment']),
    amountCents: z.int().gte(-9007199254740991).lte(9007199254740991),
    method: z.enum([
        'cash',
        'transfer',
        'other'
    ]),
    paidAt: z.string(),
    note: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    recordedByName: z.string(),
    createdAt: z.string()
});

/**
 * MemberDetail
 *
 * Full back-office view of a member
 */
export const zMemberDetail = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    membershipNumber: z.string(),
    name: z.string(),
    identifiers: zMemberIdentifiers,
    status: zMemberStatus,
    roles: z.array(zUserRole),
    profile: zMemberProfile,
    fee: zFeeSummary,
    joinedAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    version: z.int().gte(-9007199254740991).lte(9007199254740991),
    statusHistory: z.array(zMemberStatusChange),
    payments: z.array(zMemberPayment)
});

/**
 * MembershipPaymentKind
 *
 * A correction is recorded as an "adjustment" row, never by editing a payment
 */
export const zMembershipPaymentKind = z.enum(['payment', 'adjustment']);

/**
 * MembershipPaymentMethod
 *
 * How a membership-fee payment was made ("online" is reserved for lot 5)
 */
export const zMembershipPaymentMethod = z.enum([
    'cash',
    'transfer',
    'other'
]);

/**
 * RecordFeePayment
 *
 * Record a membership-fee payment (positive) or an adjustment (any non-zero)
 */
export const zRecordFeePayment = z.object({
    kind: zMembershipPaymentKind,
    amountCents: z.int().gte(-9007199254740991).lte(9007199254740991),
    method: zMembershipPaymentMethod,
    paidAt: z.string(),
    note: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * FeePaymentsList
 *
 * All recorded payments and adjustments against a member’s fee
 */
export const zFeePaymentsList = z.array(zMemberPayment);

/**
 * MemberSelf
 *
 * The signed-in member’s own account
 */
export const zMemberSelf = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    membershipNumber: z.string(),
    name: z.string(),
    identifiers: zMemberIdentifiers,
    status: zMemberStatus,
    roles: z.array(zUserRole),
    profile: zMemberProfile,
    fee: zFeeSummary,
    joinedAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * CartLine
 *
 * A line in the caller's cart. isValid is false once the product is archived or no longer offers this ordering mode — the line is still returned, not dropped, until checkout.
 */
export const zCartLine = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    product: z.object({
        id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        name: z.string(),
        saleMode: z.enum(['unit', 'weight']),
        photos: z.array(z.string())
    }),
    orderingMode: z.enum(['pre_order', 'in_store']),
    quantity: z.number().gt(0),
    unitPriceEur: z.number().gt(0),
    lineTotalEur: z.number().gt(0),
    isValid: z.boolean(),
    invalidReason: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

/**
 * Cart
 *
 * The sum of its valid lines
 */
export const zCart = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    lines: z.array(zCartLine),
    totalEur: z.number().gte(0),
    version: z.int().gte(-9007199254740991).lte(9007199254740991)
});

/**
 * OrderingModeChoice
 *
 * One concrete ordering type — never "both". Types a cart line and an order. A product that supports "both" is resolved to one of these when the member adds it to the cart.
 */
export const zOrderingModeChoice = z.enum(['pre_order', 'in_store']);

/**
 * AddCartLine
 *
 * quantity is a piece count (integer) for a unit-sale product, or kilograms (up to 3 decimals) for a by-weight product
 */
export const zAddCartLine = z.object({
    productId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    orderingMode: zOrderingModeChoice,
    quantity: z.number().gt(0)
});

/**
 * OrderDetail
 */
export const zOrderDetail = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    orderingMode: z.enum(['pre_order', 'in_store']),
    status: z.enum(['pending', 'cancelled']),
    totalEur: z.number().gte(0),
    placedAt: z.string(),
    cancelledAt: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    version: z.int().gte(-9007199254740991).lte(9007199254740991),
    lines: z.array(z.object({
        id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        productName: z.string(),
        quantity: z.number().gt(0),
        unitPriceEur: z.number().gt(0),
        lineTotalEur: z.number().gt(0)
    }))
});

/**
 * CheckoutResult
 *
 * One order per ordering type present in the cart. droppedLines lists products removed from checkout because they became unorderable (archived, or no longer offering the cart line's ordering mode) since they were added.
 */
export const zCheckoutResult = z.object({
    orders: z.array(zOrderDetail),
    droppedLines: z.array(z.object({
        productName: z.string(),
        reason: z.string()
    }))
});

/**
 * OrderStatus
 *
 * pending is the only starting value in lot 2; later lots add processing/fulfilment values to this same field
 */
export const zOrderStatus = z.enum(['pending', 'cancelled']);

/**
 * OrderLine
 *
 * An immutable snapshot, taken at checkout
 */
export const zOrderLine = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    productName: z.string(),
    quantity: z.number().gt(0),
    unitPriceEur: z.number().gt(0),
    lineTotalEur: z.number().gt(0)
});

/**
 * TestSeedResetResponse
 *
 * Result of truncating the E2E database and re-running the E2E seeder
 */
export const zTestSeedResetResponse = z.object({
    ok: z.literal(true),
    reseeded: z.boolean(),
    truncatedTables: z.int().gte(0).lte(9007199254740991)
});

/**
 * PaginationQuerySchema
 *
 * Schema for pagination query
 */
export const zPaginationQuerySchema = z.object({
    offset: z.int().gte(0).lte(9007199254740991).default(0),
    pageSize: z.int().gte(1).lte(100).default(20)
});

/**
 * FilterQueryStringSchema
 *
 * Filtering query string, in the format of "property:rule[:value];property:rule[:value];..."
 * <br> Available rules: eq, neq, gt, gte, lt, lte, like, nlike, in, nin, isnull, isnotnull
 * <br> Available properties: status, feeState, role, q
 */
export const zFilterQueryStringSchema = z.string();

/**
 * SortingQueryStringSchema
 *
 * Schema for sorting items
 */
export const zSortingQueryStringSchema = z.string();

export const zAdminMembersControllerListFilterItem = z.object({
    property: z.union([
        z.literal('status'),
        z.literal('feeState'),
        z.literal('role'),
        z.literal('q')
    ]),
    rule: z.enum([
        'eq',
        'neq',
        'gt',
        'gte',
        'lt',
        'lte',
        'like',
        'nlike',
        'in',
        'nin',
        'isnull',
        'isnotnull'
    ]),
    value: z.optional(z.string())
});

export const zAdminMembersControllerListFilterArray = z.array(zAdminMembersControllerListFilterItem);

export const zAdminMembersControllerListSortItem = z.object({
    property: z.union([
        z.literal('createdAt'),
        z.literal('name')
    ]),
    direction: z.enum(['asc', 'desc'])
});

export const zAdminMembersControllerListSortArray = z.array(zAdminMembersControllerListSortItem);

export const zAdminSuppliersControllerListFilterItem = z.object({
    property: z.union([
        z.literal('type'),
        z.literal('q')
    ]),
    rule: z.enum([
        'eq',
        'neq',
        'gt',
        'gte',
        'lt',
        'lte',
        'like',
        'nlike',
        'in',
        'nin',
        'isnull',
        'isnotnull'
    ]),
    value: z.optional(z.string())
});

export const zAdminSuppliersControllerListFilterArray = z.array(zAdminSuppliersControllerListFilterItem);

export const zAdminProductsControllerListFilterItem = z.object({
    property: z.union([
        z.literal('supplierId'),
        z.literal('categoryId'),
        z.literal('saleMode'),
        z.literal('label'),
        z.literal('q')
    ]),
    rule: z.enum([
        'eq',
        'neq',
        'gt',
        'gte',
        'lt',
        'lte',
        'like',
        'nlike',
        'in',
        'nin',
        'isnull',
        'isnotnull'
    ]),
    value: z.optional(z.string())
});

export const zAdminProductsControllerListFilterArray = z.array(zAdminProductsControllerListFilterItem);

export const zAdminProductsControllerListSortItem = z.object({
    property: z.union([
        z.literal('name'),
        z.literal('createdAt')
    ]),
    direction: z.enum(['asc', 'desc'])
});

export const zAdminProductsControllerListSortArray = z.array(zAdminProductsControllerListSortItem);

export const zShopCatalogControllerListProductsFilterItem = z.object({
    property: z.union([
        z.literal('categoryId'),
        z.literal('q')
    ]),
    rule: z.enum([
        'eq',
        'neq',
        'gt',
        'gte',
        'lt',
        'lte',
        'like',
        'nlike',
        'in',
        'nin',
        'isnull',
        'isnotnull'
    ]),
    value: z.optional(z.string())
});

export const zShopCatalogControllerListProductsFilterArray = z.array(zShopCatalogControllerListProductsFilterItem);

export const zShopCatalogControllerListProductsSortItem = z.object({
    property: z.union([
        z.literal('name'),
        z.literal('createdAt')
    ]),
    direction: z.enum(['asc', 'desc'])
});

export const zShopCatalogControllerListProductsSortArray = z.array(zShopCatalogControllerListProductsSortItem);

export const zAppControllerGetHelloData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAdminMembersControllerListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        filter: z.optional(zAdminMembersControllerListFilterArray),
        sort: z.optional(zAdminMembersControllerListSortArray),
        offset: z.int().gte(0).lte(9007199254740991).default(0),
        pageSize: z.int().gte(1).lte(100).default(20)
    })
});

/**
 * A paginated list of members
 */
export const zAdminMembersControllerListResponse = zMembersList;

export const zAdminMembersControllerCreateData = z.object({
    body: z.object({
        name: z.string().min(2),
        email: z.optional(z.union([
            z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
            z.null()
        ])),
        phoneNumber: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        profile: z.optional(z.object({
            addressLine1: z.optional(z.union([
                z.string(),
                z.null()
            ])),
            addressLine2: z.optional(z.union([
                z.string(),
                z.null()
            ])),
            postalCode: z.optional(z.union([
                z.string(),
                z.null()
            ])),
            city: z.optional(z.union([
                z.string(),
                z.null()
            ])),
            phone: z.optional(z.union([
                z.string(),
                z.null()
            ]))
        })),
        roles: z.array(z.enum(['member', 'admin'])).min(1).default(['member']),
        status: z.enum(['pending', 'active'])
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Full back-office view of a member
 */
export const zAdminMembersControllerCreateResponse = zMemberDetail;

export const zAdminMembersControllerDetailData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Full back-office view of a member
 */
export const zAdminMembersControllerDetailResponse = zMemberDetail;

export const zAdminMembersControllerDecideData = z.object({
    body: z.union([
        z.object({
            decision: z.literal('validate'),
            version: z.int().gte(-9007199254740991).lte(9007199254740991)
        }),
        z.object({
            decision: z.literal('reject'),
            reason: z.string().min(1),
            version: z.int().gte(-9007199254740991).lte(9007199254740991)
        })
    ]),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Full back-office view of a member
 */
export const zAdminMembersControllerDecideResponse = zMemberDetail;

export const zAdminMembersControllerUpdateProfileData = z.object({
    body: z.object({
        addressLine1: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        addressLine2: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        postalCode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        city: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        phone: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        name: z.optional(z.string().min(2)),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Full back-office view of a member
 */
export const zAdminMembersControllerUpdateProfileResponse = zMemberDetail;

export const zAdminMembersControllerSetFeeData = z.object({
    body: z.object({
        expectedAmountCents: z.int().gte(0).lte(9007199254740991),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Membership-fee expectation, total paid, and derived state
 */
export const zAdminMembersControllerSetFeeResponse = zFeeSummary;

export const zAdminMembersControllerListFeePaymentsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * All recorded payments and adjustments against a member’s fee
 */
export const zAdminMembersControllerListFeePaymentsResponse = zFeePaymentsList;

export const zAdminMembersControllerRecordFeePaymentData = z.object({
    body: z.object({
        kind: z.enum(['payment', 'adjustment']),
        amountCents: z.int().gte(-9007199254740991).lte(9007199254740991),
        method: z.enum([
            'cash',
            'transfer',
            'other'
        ]),
        paidAt: z.string(),
        note: z.optional(z.union([
            z.string(),
            z.null()
        ]))
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Membership-fee expectation, total paid, and derived state
 */
export const zAdminMembersControllerRecordFeePaymentResponse = zFeeSummary;

export const zAdminMembersControllerSetRolesData = z.object({
    body: z.object({
        roles: z.array(z.enum(['member', 'admin'])).min(1),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Full back-office view of a member
 */
export const zAdminMembersControllerSetRolesResponse = zMemberDetail;

export const zAdminMembersControllerTerminateData = z.object({
    body: z.object({
        reason: z.string().min(1),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Full back-office view of a member
 */
export const zAdminMembersControllerTerminateResponse = zMemberDetail;

export const zAdminMembersControllerReactivateData = z.object({
    body: z.object({
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Full back-office view of a member
 */
export const zAdminMembersControllerReactivateResponse = zMemberDetail;

export const zMemberSelfControllerMeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * The signed-in member’s own account
 */
export const zMemberSelfControllerMeResponse = zMemberSelf;

export const zMemberSelfControllerUpdateProfileData = z.object({
    body: z.object({
        addressLine1: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        addressLine2: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        postalCode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        city: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        phone: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        name: z.optional(z.string().min(2)),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * The signed-in member’s own account
 */
export const zMemberSelfControllerUpdateProfileResponse = zMemberSelf;

export const zMemberSelfControllerTerminateData = z.object({
    body: z.object({
        confirm: z.literal(true)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * The signed-in member’s own account
 */
export const zMemberSelfControllerTerminateResponse = zMemberSelf;

export const zMembershipIntakeControllerGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Whether self-registration is currently accepted
 */
export const zMembershipIntakeControllerGetResponse = zMembershipIntake;

export const zMembershipIntakeControllerSetData = z.object({
    body: z.object({
        open: z.boolean()
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Whether self-registration is currently accepted
 */
export const zMembershipIntakeControllerSetResponse = zMembershipIntake;

export const zAdminSuppliersControllerListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        includeArchived: z.string(),
        filter: z.optional(zAdminSuppliersControllerListFilterArray),
        offset: z.int().gte(0).lte(9007199254740991).default(0),
        pageSize: z.int().gte(1).lte(100).default(20)
    })
});

/**
 * A paginated list of suppliers
 */
export const zAdminSuppliersControllerListResponse = zCatalogSuppliersList;

export const zAdminSuppliersControllerCreateData = z.object({
    body: z.object({
        name: z.string().min(1),
        type: z.enum(['producer', 'wholesaler']),
        contactName: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        contactEmail: z.optional(z.union([
            z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
            z.null()
        ])),
        contactPhone: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        notes: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        deliveryMode: z.optional(z.union([
            z.enum(['livraison', 'collecte']),
            z.null()
        ])),
        referentId: z.optional(z.union([
            z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            z.null()
        ])),
        producerCategoryIds: z.optional(z.union([
            z.array(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)),
            z.null()
        ]))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * A source of products
 */
export const zAdminSuppliersControllerCreateResponse = zCatalogSupplier;

export const zAdminSuppliersControllerGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A source of products
 */
export const zAdminSuppliersControllerGetResponse = zCatalogSupplier;

export const zAdminSuppliersControllerUpdateData = z.object({
    body: z.object({
        name: z.optional(z.string().min(1)),
        type: z.optional(z.enum(['producer', 'wholesaler'])),
        contactName: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        contactEmail: z.optional(z.union([
            z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
            z.null()
        ])),
        contactPhone: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        notes: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        deliveryMode: z.optional(z.union([
            z.enum(['livraison', 'collecte']),
            z.null()
        ])),
        referentId: z.optional(z.union([
            z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            z.null()
        ])),
        producerCategoryIds: z.optional(z.union([
            z.array(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)),
            z.null()
        ])),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A source of products
 */
export const zAdminSuppliersControllerUpdateResponse = zCatalogSupplier;

export const zAdminSuppliersControllerArchiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.object({
        cascade: z.string()
    })
});

/**
 * A source of products
 */
export const zAdminSuppliersControllerArchiveResponse = zCatalogSupplier;

export const zAdminSuppliersControllerUnarchiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A source of products
 */
export const zAdminSuppliersControllerUnarchiveResponse = zCatalogSupplier;

export const zAdminReferentsControllerListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * All referents
 */
export const zAdminReferentsControllerListResponse = zCatalogReferentsList;

export const zAdminReferentsControllerCreateData = z.object({
    body: z.object({
        firstName: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        lastName: z.string().min(1),
        contactEmail: z.optional(z.union([
            z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
            z.null()
        ])),
        contactPhone: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        userId: z.optional(z.union([
            z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            z.null()
        ]))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * The co-op member who follows a supplier
 */
export const zAdminReferentsControllerCreateResponse = zCatalogReferent;

export const zAdminReferentsControllerDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zAdminReferentsControllerDeleteResponse = z.void();

export const zAdminReferentsControllerGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * The co-op member who follows a supplier
 */
export const zAdminReferentsControllerGetResponse = zCatalogReferent;

export const zAdminReferentsControllerUpdateData = z.object({
    body: z.object({
        firstName: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        lastName: z.optional(z.string().min(1)),
        contactEmail: z.optional(z.union([
            z.email().regex(/^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
            z.null()
        ])),
        contactPhone: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        userId: z.optional(z.union([
            z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            z.null()
        ])),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * The co-op member who follows a supplier
 */
export const zAdminReferentsControllerUpdateResponse = zCatalogReferent;

export const zAdminCategoriesControllerListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        includeArchived: z.string()
    })
});

/**
 * All categories (one nesting level)
 */
export const zAdminCategoriesControllerListResponse = zCatalogCategoriesList;

export const zAdminCategoriesControllerCreateData = z.object({
    body: z.object({
        name: z.string().min(1),
        parentId: z.optional(z.union([
            z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            z.null()
        ]))
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * A grouping for products in the catalogue
 */
export const zAdminCategoriesControllerCreateResponse = zCatalogCategory;

export const zAdminCategoriesControllerUpdateData = z.object({
    body: z.object({
        name: z.optional(z.string().min(1)),
        parentId: z.optional(z.union([
            z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
            z.null()
        ])),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A grouping for products in the catalogue
 */
export const zAdminCategoriesControllerUpdateResponse = zCatalogCategory;

export const zAdminCategoriesControllerArchiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A grouping for products in the catalogue
 */
export const zAdminCategoriesControllerArchiveResponse = zCatalogCategory;

export const zAdminCategoriesControllerUnarchiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A grouping for products in the catalogue
 */
export const zAdminCategoriesControllerUnarchiveResponse = zCatalogCategory;

export const zAdminProducerCategoriesControllerListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        includeArchived: z.string()
    })
});

/**
 * All producer categories
 */
export const zAdminProducerCategoriesControllerListResponse = zCatalogProducerCategoriesList;

export const zAdminProducerCategoriesControllerCreateData = z.object({
    body: z.object({
        name: z.string().min(1)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * A tag for what a supplier produces (e.g. "Boissons", "Fromages")
 */
export const zAdminProducerCategoriesControllerCreateResponse = zCatalogProducerCategory;

export const zAdminProducerCategoriesControllerUpdateData = z.object({
    body: z.object({
        name: z.optional(z.string().min(1)),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A tag for what a supplier produces (e.g. "Boissons", "Fromages")
 */
export const zAdminProducerCategoriesControllerUpdateResponse = zCatalogProducerCategory;

export const zAdminProducerCategoriesControllerArchiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A tag for what a supplier produces (e.g. "Boissons", "Fromages")
 */
export const zAdminProducerCategoriesControllerArchiveResponse = zCatalogProducerCategory;

export const zAdminProducerCategoriesControllerUnarchiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A tag for what a supplier produces (e.g. "Boissons", "Fromages")
 */
export const zAdminProducerCategoriesControllerUnarchiveResponse = zCatalogProducerCategory;

export const zAdminProductsControllerListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        includeArchived: z.string(),
        filter: z.optional(zAdminProductsControllerListFilterArray),
        sort: z.optional(zAdminProductsControllerListSortArray),
        offset: z.int().gte(0).lte(9007199254740991).default(0),
        pageSize: z.int().gte(1).lte(100).default(20)
    })
});

/**
 * A paginated list of products
 */
export const zAdminProductsControllerListResponse = zCatalogProductsList;

export const zAdminProductsControllerCreateData = z.object({
    body: z.object({
        name: z.string().min(1),
        description: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        supplierId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        categoryId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        saleMode: z.enum(['unit', 'weight']),
        orderingMode: z.enum([
            'pre_order',
            'in_store',
            'both'
        ]),
        photos: z.array(z.string()).default([]),
        labels: z.array(z.enum([
            'organic',
            'local',
            'vegetarian',
            'vegan'
        ])).default([]),
        barcode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        averageWeightGrams: z.optional(z.union([
            z.int().gt(0).lte(9007199254740991),
            z.null()
        ])),
        weightTolerancePercent: z.optional(z.union([
            z.int().gt(0).lte(9007199254740991),
            z.null()
        ])),
        initialPriceEur: z.number().gt(0)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * A product with its full price history
 */
export const zAdminProductsControllerCreateResponse = zCatalogProductDetail;

export const zAdminProductsControllerGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A product with its full price history
 */
export const zAdminProductsControllerGetResponse = zCatalogProductDetail;

export const zAdminProductsControllerUpdateData = z.object({
    body: z.object({
        name: z.optional(z.string().min(1)),
        description: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        supplierId: z.optional(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)),
        categoryId: z.optional(z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)),
        saleMode: z.optional(z.enum(['unit', 'weight'])),
        orderingMode: z.optional(z.enum([
            'pre_order',
            'in_store',
            'both'
        ])),
        photos: z.optional(z.array(z.string())).default([]),
        labels: z.optional(z.array(z.enum([
            'organic',
            'local',
            'vegetarian',
            'vegan'
        ]))).default([]),
        barcode: z.optional(z.union([
            z.string(),
            z.null()
        ])),
        averageWeightGrams: z.optional(z.union([
            z.int().gt(0).lte(9007199254740991),
            z.null()
        ])),
        weightTolerancePercent: z.optional(z.union([
            z.int().gt(0).lte(9007199254740991),
            z.null()
        ])),
        version: z.int().gte(-9007199254740991).lte(9007199254740991)
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A product with its full price history
 */
export const zAdminProductsControllerUpdateResponse = zCatalogProductDetail;

export const zAdminProductsControllerSetPriceData = z.object({
    body: z.object({
        amountEur: z.number().gt(0),
        effectiveFrom: z.optional(z.string())
    }),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A product with its full price history
 */
export const zAdminProductsControllerSetPriceResponse = zCatalogProductDetail;

export const zAdminProductsControllerArchiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * An item the cooperative offers
 */
export const zAdminProductsControllerArchiveResponse = zCatalogProduct;

export const zAdminProductsControllerUnarchiveData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * An item the cooperative offers
 */
export const zAdminProductsControllerUnarchiveResponse = zCatalogProduct;

export const zShopCatalogControllerListCategoriesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Categories that currently have at least one orderable product
 */
export const zShopCatalogControllerListCategoriesResponse = zShopCategoriesList;

export const zShopCatalogControllerListProductsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        filter: z.optional(zShopCatalogControllerListProductsFilterArray),
        sort: z.optional(zShopCatalogControllerListProductsSortArray),
        offset: z.int().gte(0).lte(9007199254740991).default(0),
        pageSize: z.int().gte(1).lte(100).default(20)
    })
});

/**
 * A paginated list of orderable products
 */
export const zShopCatalogControllerListProductsResponse = zShopProductsList;

export const zShopCatalogControllerGetProductData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * A product detail page shown in the public shop — narrower than the admin detail
 */
export const zShopCatalogControllerGetProductResponse = zShopProductDetail;

export const zCartControllerGetCartData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * The sum of its valid lines
 */
export const zCartControllerGetCartResponse = zCart;

export const zCartControllerAddLineData = z.object({
    body: z.object({
        productId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
        orderingMode: z.enum(['pre_order', 'in_store']),
        quantity: z.number().gt(0)
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * The sum of its valid lines
 */
export const zCartControllerAddLineResponse = zCart;

export const zCartControllerRemoveLineData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        lineId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * The sum of its valid lines
 */
export const zCartControllerRemoveLineResponse = zCart;

export const zCartControllerUpdateLineData = z.object({
    body: z.object({
        quantity: z.number().gt(0)
    }),
    path: z.object({
        lineId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * The sum of its valid lines
 */
export const zCartControllerUpdateLineResponse = zCart;

export const zCartControllerCheckoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * One order per ordering type present in the cart. droppedLines lists products removed from checkout because they became unorderable (archived, or no longer offering the cart line's ordering mode) since they were added.
 */
export const zCartControllerCheckoutResponse = zCheckoutResult;
