// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAppControllerGetHelloData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});
